apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::481028758247:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-X09T7NHG2IKE
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::481028758247:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- rolearn: arn:aws:iam::481028758247:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-X09T7NHG2IKE\n  username: system:node:{{EC2PrivateDNSName}}\n  groups:\n    - system:bootstrappers\n    - system:nodes\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"aws-auth","namespace":"kube-system"}}
  creationTimestamp: "2020-06-12T12:57:30Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1292"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: bf2339be-264a-4315-815b-3738170445e1
