apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::481028758247:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-X09T7NHG2IKE
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
        - system:masters
        rolearn: arn:aws:iam::481028758247:role/UdacityFlaskDeployCBKubectlRole
        username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-06-12T12:57:30Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1292"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: bf2339be-264a-4315-815b-3738170445e1
