apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::481028758247:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1902TB3Y1JWO4
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - rolearn: arn:aws:iam::481028758247:user/wow
      username: wow
      groups:
        - system:masters
kind: ConfigMap
metadata:
  creationTimestamp: "2020-06-13T13:09:38Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "6896"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 31a692b9-d6af-4669-be68-55196199a60b
