apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::776127788702:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-CKKC0VNGBROE
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
        - system:masters
    - rolearn: arn:aws:iam::776127788702:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:bootstrappers
        - system:nodes
        - system:masters
  mapUsers: |
    - userarn: arn:aws:iam::776127788702:user/evo
      username: evo
      groups:
        - system:masters
kind: ConfigMap
metadata:
  creationTimestamp: "2020-06-13T20:34:11Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "38385"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: cc9ea8f3-5938-4aa7-98b5-dad0564e5dd0
