apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::481028758247:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1LPPWLWFGI2ZX
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
        - system:masters
    - rolearn: arn:aws:iam::481028758247:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:bootstrappers
        - system:nodes
        - system:masters
  mapUsers: |
    - userarn: arn:aws:iam::481028758247:user/wow
      username: wow
      gruops:
        - system:masters
kind: ConfigMap
metadata:
  creationTimestamp: "2020-06-12T22:40:53Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "86717"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 2560c0c8-5280-4a3f-8169-97a3df3f1f72
