apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::776127788702:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-K62ST2RLKT3A
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::776127788702:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-06-14T09:12:58Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1557"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 8e3c6e0b-a2d9-41d4-b715-66bbf70a6ba3
