apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::481028758247:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1IROAXV45WJUL
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::481028758247:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-06-12T22:40:53Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "9087"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 2560c0c8-5280-4a3f-8169-97a3df3f1f72